### ISSUE TITLE
Could not set temporary folder config warning

### ISSUE THREAD

**Issue by wahabk** [felixchenier/kineticstoolkit#52]
`/home/wahab/code/anaconda3/lib/python3.8/site-packages/kineticstoolkit/config.py:78: UserWarning: Could not set temporary folder.
  warnings.warn('Could not set temporary folder.')`

**Describe the bug**

Hello first of all this package is fantastic!! brilliant work

I have installed ktk using conda3 and I'm getting a temp folder warning and not sure how to fix this, it looks like its somewhere in config.py:66 

`elif is_mac or is_linux:
        _base_temp_folder = os.environ['TMPDIR']`

when i try to print `os.environ['TMPDIR']` it gives a KeyError because its None, is this to do with conda? I usually use virtualenv but have to use conda for this project

would be happy to create a PR if you can point me in the right direction

**To Reproduce**

`import kineticstoolkit as ktk`

**Expected behavior**

**Screenshots**
NA
**Python installation**
Anaconda3 conda-forge

**Operating system**
Linux
Ubuntu 20.04

**Additional context**
NA

**Comment by felixchenier** [comment]
Good morning @wahabk 

Thanks for finding this package useful ! I certainly do too 😄 

I admit that I test more on macOS than Linux since this is my OS. I think I solved the problem, could you try pulling branch "bug/#52" to see if it works? If it does, I'll merge it to master.

Thanks,

Felix

**Comment by wahabk** [comment]
Brilliant :) that fixed it! thank you so much
