### ISSUE TITLE
Can't remove all events via TimeSeries.ui_edit_events()

### ISSUE THREAD

**Issue by alcantarar** [felixchenier/kineticstoolkit#67]
**Describe the bug**
Using the wheelchair data in the tutorial, I can add/remove singular events using `TimeSeries.ui_edit_events()`, but when I select "Remove all events" and confirm the warning, the UI prompts me to "Select an event on the figure". If I do, I receive a `ValueError: attempt to get argmin of an empty sequence` error. 

**To Reproduce**
```
ts = ktk.TimeSeries.from_database(df)
ts = ts.add_event(4, 'test')
ts = ts.ui_edit_events()
# select "remove all events", confirm selection. Then prompted to "Select and event on figure".
```
Traceback
```
Traceback (most recent call last):

  File "<ipython-input-73-e52ae1eb1eb7>", line 1, in <module>
    ts = ts.ui_edit_events()

  File "...\kineticstoolkit\kineticstoolkit\timeseries.py", line 1090, in ui_edit_events
    event_index = get_event_index(ts)

  File "...\kineticstoolkit\kineticstoolkit\timeseries.py", line 992, in get_event_index
    return int(np.argmin(np.abs(event_times - this_time)))

  File "<__array_function__ internals>", line 5, in argmin

  File "...\Anaconda3\envs\ktk\lib\site-packages\numpy\core\fromnumeric.py", line 1274, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "...\Anaconda3\envs\ktk\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence
```

**Expected behavior**
I would expect all events to be removed from the plot instead of prompted to select an event.

**Screenshots**

**Python installation**
ktk 3.8 environment via anaconda install instructions.

**Operating system**
Windows 10.

**Additional context**

**Comment by felixchenier** [comment]
Thank you very much @alcantarar for this detailed bug report. I confirm that I can reproduce it and I just resolved it in master. That part of the code was weird enough, probably due to a conflicting merge that went wrong.

Thank you also for your reviewing of the paper in JOSS. I hope some of this toolkit can be useful for somebody else :-)

Best,

Félix
