### ISSUE TITLE
Condition for the filename when using ktk.kinematics.read_c3d_file(filename)

### ISSUE THREAD

**Issue by Fleu33** [felixchenier/kineticstoolkit#82]
**Describe the bug**
When utilizing  ktk.kinematics.read_c3d_file(filename), there is an error "OSError: Could not open the c3d file: iostream stream error" if the filename contain spaces or "é".

**To Reproduce**
1. Name your folder or file with space or "é".
2. Use the .get() function to get the filename.
3. Use ktk.kinematics.read_c3d_file(filename).

**Expected behavior**
I was expecting to open the c3d file and extract the TimeSeries.

**Screenshots**

![Bug](https://user-images.githubusercontent.com/92494465/155180618-2806e3d2-b3a7-4eea-9b6c-b5b629779183.png)

**Python installation**
Select: Miniconda

**Operating system**
 - Windows 11

**Additional context**
When getting rid of the spaces and "é", everything work perfectly.

**Comment by felixchenier** [comment]
Note: I don't have this bug on macOS

**Comment by felixchenier** [comment]
I do have the bug on Windows. This is an ezc3d bug, I filed it on https://github.com/pyomeca/ezc3d/issues/252

Let's see what happens, and if we need a workaround.

**Comment by felixchenier** [comment]
ezc3d only supports UTF-8 naming. I'll try to make a workaround.
